name: Build VMProtect-Unpacker

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Setup vcpkg
        shell: pwsh
        run: |
          git clone https://github.com/microsoft/vcpkg.git C:\vcpkg
          C:\vcpkg\bootstrap-vcpkg.bat

      - name: Install dependencies
        shell: pwsh
        run: |
          C:\vcpkg\vcpkg.exe install unicorn:x64-windows zydis:x64-windows

      - name: Build Release x64
        shell: pwsh
        run: |
          msbuild VMProtect.sln `
            /m `
            /p:Configuration=Release `
            /p:Platform=x64 `
            /p:VcpkgRoot=C:\vcpkg\ `
            /p:VcpkgInstalled=C:\vcpkg\installed\x64-windows

      - name: Find EXE
        shell: pwsh
        run: |
          Get-ChildItem -Path . -Filter *.exe -Recurse | ForEach-Object {
            Write-Host $_.FullName
          }

      - name: Collect runtime files
        shell: pwsh
        run: |
          New-Item -ItemType Directory -Force -Path artifact | Out-Null

          Copy-Item "x64\Release\VMProtect.exe" "artifact\"

          Copy-Item "C:\vcpkg\installed\x64-windows\bin\unicorn.dll" "artifact\"
          Copy-Item "C:\vcpkg\installed\x64-windows\bin\Zydis.dll" "artifact\"
          Copy-Item "C:\vcpkg\installed\x64-windows\bin\Zycore.dll" "artifact\"

          Get-ChildItem artifact

      - name: Upload build
        uses: actions/upload-artifact@v4
        with:
          name: VMProtect-Unpacker-x64
          path: artifact/*
          if-no-files-found: error
